# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  terraform-plan:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: ls file
          command: ls terraform
      - run:
          name: save to local
          command: echo $terraform_context_key > /terraform/terraform_context_key.json
      - run:
          name: ls file
          command: ls terraform
      - run:
          name: terraform init
          command: |
            cd terraform
            terraform init --upgrade \
            -var 
            terraform plan
  terraform-apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform apply
          command: |
            cd terraform
            terraform apply --auto-approve

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  terraform-plan-apply-destroy:
    jobs:
      - terraform-plan:
          context:
            - mb_terraform_context
      - terraform-apply:
          context:
            - mb_terraform_context
          requires:
            - terraform-plan

